language: php

php:
  - 7.1
  - 7.2

before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan clear-compiled
  - php artisan optimize

script:
  - php artisan key:generate
  - vendor/bin/phpunit

cache:
  directories:
    - vendor